DROP DATABASE IF EXISTS `ticket-selling-system-db`;
CREATE DATABASE `ticket-selling-system-db`;
USE `ticket-selling-system-db`;

DROP TABLE IF EXISTS users;
CREATE TABLE users (
id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT UNIQUE,
username VARCHAR(255) NOT NULL UNIQUE,
`password` VARCHAR(255) NOT NULL,
first_name VARCHAR(255) NOT NULL,
last_name VARCHAR(255) NOT NULL,
email VARCHAR(255),
`role` ENUM('cashier', 'administrator') NOT NULL
);



DROP TABLE IF EXISTS artists;
CREATE TABLE artists (
id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT UNIQUE,
dj_name VARCHAR(255) UNIQUE,
first_name VARCHAR(255),
last_name VARCHAR(255),
email VARCHAR(255)
);

DROP TABLE IF EXISTS genres;
CREATE TABLE genres (
id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT UNIQUE,
genre VARCHAR(255) NOT NULL UNIQUE
);

DROP TABLE IF EXISTS shows;
CREATE TABLE shows (
id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT UNIQUE,
genre_id BIGINT NOT NULL REFERENCES genres (id),
artist_id BIGINT NOT NULL REFERENCES artists (id),
title VARCHAR(255) NOT NULL UNIQUE,
`date` TIMESTAMP,
nr_of_tickets INT NOT NULL
);

DROP TABLE IF EXISTS tickets;
CREATE TABLE tickets (
id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT UNIQUE,
show_id BIGINT NOT NULL REFERENCES shows (id),
nr_of_places INT NOT NULL
);